# Generated by Django 4.2.1 on 2023-07-15 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Age must be a positive integer.'), django.core.validators.MaxValueValidator(150, message='Age must be less than or equal to 150.')])),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
